### PR TITLE
Updates to AVISO processing script

### PR DESCRIPTION
**Pull request by jkrasting**
@chiaweh2 - I ran into some issues running the obs. processing scripts. I made some edits for efficiency and readability.  Could you please review these, test them, and look it over for scientific consistency with your previously generated files?

### CODE REVIEW

**Comment by chiaweh2** [comment]
Hi @jkrasting -- It works great. Thank you for the PR! The only thing is that my original version is trying to avoid using [`xarray.open_mfdataset` since it require the install of `Dask`](http://xarray.pydata.org/en/stable/generated/xarray.open_mfdataset.html). However, if Dask has been added to the MDTF module list in the python3 conda env. I agree that using `xarray.open_mfdataset` is a better solution.

**Comment by jkrasting** [comment]
@chiaweh2 - I think we can do that, right @wrongkindofdoctor?

**Comment by chiaweh2** [comment]
@jkrasting That is great! Once @wrongkindofdoctor confirm it is possible to include Dask. I will merge the pull request!

**Comment by wrongkindofdoctor** [comment]
Per this week's meeting discussion, we can include Dask in the python3 conda environment file. I will open an issue for this.

**Pull request merged**
